//LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//LOGOUT
export const USER_LOGOUT = 'USER_LOGOUT';

//REGISTER
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USERDISPLAYPARKINGS
export const USER_DISPLAY_PARKINGS_REQUEST = 'USER_DISPLAY_PARKINGS_REQUEST';
export const USER_DISPLAY_PARKINGS_SUCCESS = 'USER_DISPLAY_PARKINGS_SUCCESS';
export const USER_DISPLAY_PARKINGS_FAIL = 'USER_DISPLAY_PARKINGS_FAIL';
