//LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//LOGOUT
export const USER_LOGOUT = 'USER_LOGOUT';

//REGISTER
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USERDISPLAYPARKINGS
export const USER_DISPLAY_PARKINGS_REQUEST = 'USER_DISPLAY_PARKINGS_REQUEST';
export const USER_DISPLAY_PARKINGS_SUCCESS = 'USER_DISPLAY_PARKINGS_SUCCESS';
export const USER_DISPLAY_PARKINGS_FAIL = 'USER_DISPLAY_PARKINGS_FAIL';

//USERCREATEPARKINGS
export const USER_CREATE_PARKINGS_REQUEST = 'USER_CREATE_PARKINGS_REQUEST';
export const USER_CREATE_PARKINGS_SUCCESS = 'USER_CREATE_PARKINGS_SUCCESS';
export const USER_CREATE_PARKINGS_FAIL = 'USER_CREATE_PARKINGS_FAIL';

//USERMYPARKINGS
export const USER_MY_PARKINGS_REQUEST = 'USER_MY_PARKINGS_REQUEST';
export const USER_MY_PARKINGS_SUCCESS = 'USER_MY_PARKINGS_SUCCESS';
export const USER_MY_PARKINGS_FAIL = 'USER_MY_PARKINGS_FAIL';

//ADMINDISPLAYPARKINGS
export const ADMIN_DISPLAY_PARKINGS_REQUEST = 'ADMIN_DISPLAY_PARKINGS_REQUEST';
export const ADMIN_DISPLAY_PARKINGS_SUCCESS = 'ADMIN_DISPLAY_PARKINGS_SUCCESS';
export const ADMIN_DISPLAY_PARKINGS_FAIL = 'ADMIN_DISPLAY_PARKINGS_FAIL';

//ADMINEXCETSTATUS
export const ADMIN_EXCEPT_STATUS_REQUEST = 'ADMIN_EXCEPT_STATUS_REQUEST';
export const ADMIN_EXCEPT_STATUS_SUCCESS = 'ADMIN_EXCEPT_STATUS_SUCCESS';
export const ADMIN_EXCEPT_STATUS_FAIL = 'ADMIN_EXCEPT_STATUS_FAIL';

//ADMINCREATEPARKINGS
export const ADMIN_CREATE_PARKING_REQUEST = 'ADMIN_CREATE_PARKING_REQUEST';
export const ADMIN_CREATE_PARKING_SUCCESS = 'ADMIN_CREATE_PARKING_SUCCESS';
export const ADMIN_CREATE_PARKING_FAIL = 'ADMIN_CREATE_PARKING_FAIL';
